name: 'hello-world-action'
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: 'run checkout'
        run: ./ci/build-app.sh
      - name: 'unit tests'
        run: ./ci/unit-test-app.sh
