name: 'hello-world-action'
on: push
jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'print-hello'
        run: echo 'Hello, World!'
      - name: 'print-more'
        run: echo 'Guten huten, Frau Tuten!'