name: 'hello-world-action'
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: 'print-hello'
        run: echo 'Hello, World!'
      - name: 'print-more'
        run: echo 'Guten huten, Frau Tuten!'
  unit-test:
    runs-on: ubuntu-latest
    needs: [hello-job]
    steps:
      - name: 'unit tests'
        run: echo 'Unit tests passed!'
  integration-test:
    runs-on: ubuntu-latest
    needs: [hello-job]
    steps:
      - name: 'integration tests'
        run: echo 'Integration tests passed!'

  