name: 'hello-world-action'
on: push
jobs:
  clone-repo:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: 'run checkout'
        run: ./ci/build-app.sh
      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  unit-test:
    runs-on: ubuntu-latest
    needs: [clone-repo]
    container: gradle:6-jdk11
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: 'change permissions'
      run: chmod +x ./ci/unit-test-app.sh
    - name: 'unit tests'
      run: ./ci/unit-test-app.sh
