name: 'hello-world-action'
on: push
jobs:
  hello-job:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: 'run checkout'
        run: ./ci/build-app.sh
  unit-test:
    runs-on: ubuntu-latest
    needs: [hello-job]
    steps:
      - name: 'unit tests'
        run: echo 'Unit tests passed!'
  integration-test:
    runs-on: ubuntu-latest
    needs: [hello-job]
    steps:
      - name: 'integration tests'
        run: echo 'Integration tests passed!'

  