env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}

name: Java CI
on: push
jobs:
  clone-repo:
    name: 'Clone Repo'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Upload code
        uses: actions/upload-artifact@v2
        with:
          name: code
          path: .
  unit-test:
    name: 'Unit Test'
    runs-on: ubuntu-latest
    needs: [clone-repo]
    container: gradle:6-jdk11
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: 'change permissions'
      run: chmod +x ./ci/unit-test-app.sh
    - name: 'unit tests'
      run: ./ci/unit-test-app.sh
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    needs: [clone-repo]
    container: gradle:6-jdk11
    steps:
    - name: Download code
      uses: actions/download-artifact@v2
      with:
        name: code
        path: .
    - name: 'change permissions'
      run: chmod +x ./ci/build-app.sh
    - name: 'run checkout'
      run: ./ci/build-app.sh
    - name: Upload built code
      uses: actions/upload-artifact@v2
      with:
        name: built-code
        path: .
  docker:
    name: 'Docker Image'
    needs: [build, unit-test]
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/download-artifact@v2
        with:
          name: built-code
          path: .
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ env.docker_username }}
          password: ${{ env.docker_password }}
      - name: Export GIT-COMMIT
        run: export GIT_COMMIT="GA-$GITHUB_SHA"
      - name: Build Docker image
        run: chmod +x ./ci/build-docker.sh && ./ci/build-docker.sh
      - name: Push Docker image
        run: chmod +x ./ci/push-docker.sh && ./ci/push-docker.sh
      
